---
  # Only run "update_cache=yes" if the last one is more than more than 3600 seconds ago
  - name: fpm | Update apt-cache when needed
    apt: update_cache=yes cache_valid_time=3600

  # prerequirements
  - name: fpm | Ensure prerequirements are installed
    apt: pkg={{ item }} state=installed
    with_items:
      - git
      - wget
      - php-pear

  # Install ruby
  - include: ruby.yml

  # Install gems
  - name: fpm | Ensure FPM fpm installed
    gem: name=fpm state=present
    sudo: yes
