---
  # Only run "update_cache=yes" if the last one is more than more than 3600 seconds ago
  - apt: update_cache=yes cache_valid_time=3600

  # prerequirements
  - name: fpm | Ensure prerequirements are installed
    apt: pkg={{ item }} state=installed
    with_items:
      - git
      - wget
