---
# We're installing Ruby from source because Ubuntu has a too old
# version in it's packaging-system

- name: ruby | Install ruby dependencies
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items:
    - bison
    - build-essential
    - git-core
    - libdigest-hmac-perl
    - libffi-dev
    - libgdbm-dev
    - libncurses5-dev
    - libreadline6-dev
    - libtool
    - libyaml-dev
    - make
    - tar
    - unzip
    - zlib1g
    - zlib1g-dev

- name: ruby | Download ruby
  get_url: url=ftp://ftp.ruby-lang.org//pub/ruby/1.9/ruby-1.9.3-p286.tar.gz dest=/tmp/ruby-1.9.3-p286.tar

- name: ruby | Extract ruby
  command: tar -zxf /tmp/ruby-1.9.3-p286.tar creates=/tmp/ruby-1.9.3-p286 chdir=/tmp

- name: ruby | Make, configure, and install ruby
  command: "{{ item }} chdir=/tmp/ruby-1.9.3-p286 creates=/usr/local/bin/ruby"
  with_items:
    - ./configure
    - make
    - sudo make install
