---
  # Create root .ssh directory
  - name: ssh | create .ssh directory for root
    file: path=/root/.ssh state=directory

  # SSH - copy the config file
  - name: ssh | Put the SSH config file in place
    action: template src=files/conf/ssh_config.j2 dest=/home/vagrant/.ssh/config
