---
  # - name: put ssh-key in
  #   authorized_key: user=root key="{{lookup('file', '~/.ssh/id_dsa.pub') }}" manage_dir=yes

  # Create root .ssh directory
  - name: ssh | create .ssh directory for root
    file: path=/root/.ssh state=directory

  # SSH - copy the gitlab private (!!) SSH key
  - name: ssh | put Gitlab ssh-key in
    copy: src=~/.ssh/id_dsa dest=/home/vagrant/.ssh/ owner=vagrant mode=0400

  # SSH - copy the config file
  - name: ssh | Put the SSH config file in place
    action: template src=files/conf/ssh_config.j2 dest=/home/vagrant/.ssh/config
