---
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  sudo: true

  tasks:

  # SSH
  - include: tasks/ssh.yml

  # Update the apt-cache
  - name: apt | Update the apt cache 
    apt: update_cache=yes cache_valid_time=3600
    sudo: yes

  # Miscellaneous
  - name: apt | Ensure variaty of tools is installed
    apt: pkg={{ item }} state=installed
    with_items:
      - vim
      - curl

  # FPM
  - include: tasks/fpm.yml

  # bash_it
  - name: misc. | Download bash_it for a nice Bash environment
    git: repo=https://github.com/pauledenburg/bash_it.git dest=/home/vagrant/.bash_it 
    sudo_user: vagrant

  - name: misc. | Install bash_it
    command: ~/.bash_it/install.sh
    sudo_user: vagrant

  handlers:
    - include: handlers.yml
